# Generated by Django 4.2.15 on 2024-10-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('duration_in_days', models.IntegerField()),
                ('priority_level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(editable=False)),
                ('end_time', models.DateTimeField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscriptiontype')),
            ],
        ),
    ]
